### ISSUE TITLE
Make perfdash configurable

### ISSUE THREAD

**Issue by krzysied** [kubernetes/perf-tests#546]
Perfdash should be more configurable, so it can be set up by user to display custom runs data.

- [x] Allowing array flags #548 
- [x] Extracting job config url to flags #548 
- [x] Allowing job configs from files #560 
- [x] Replacing contrib/utils with storage client. #563 
- [x] Making storage access configurable #564 
- [x] Bump up new version and update http://perf-dash.k8s.io #566

**Comment by krzysied** [comment]
Done!
